config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :digitals
    end
  end
  
  get '/digital/:secret', :to => 'digitals#show', :via => :get, :as => 'digital', :constraints => { :secret => /[a-zA-Z0-9]{30}/ }

end

app/models/spree/calculator/digital_delivery.rb
# https://github.com/spree/spree/issues/1439
require_dependency 'spree/calculator'

module Spree
  class Calculator::DigitalDelivery < Calculator::FlatRate
    def self.description
      I18n.t(:digital_delivery)
    end

    def compute(object=nil)
      self.preferred_amount
    end

    def available?(order)
      order.digital?
    end
  end
end

app/models/spree/digital.rb
module Spree
  class Digital < ActiveRecord::Base
    belongs_to :variant
    has_many :digital_links, :dependent => :destroy
  
    has_attached_file :attachment, :path => ":rails_root/private/digitals/:id/:basename.:extension"
  
    # TODO: Limit the attachment to one single file. Paperclip supports many by default :/

    attr_accessible :variant_id, :attachment
      
  end
end

app/models/spree/digital_link.rb
module Spree
  class DigitalLink < ActiveRecord::Base
    
    belongs_to :digital
    belongs_to :line_item
    
    validates_length_of :secret, :is => 30
    validates :digital, :presence => true
    
    before_validation :set_defaults, :on => :create
    
    # Can this link stil be used? It is valid if it's less than 24 hours old and was not accessed more than 3 times
    def authorizable?
      self.created_at > Spree::DigitalConfiguration[:authorized_days].day.ago and self.access_counter < Spree::DigitalConfiguration[:authorized_clicks]
    end
    
    # This method should be called when a download is initiated.
    # It returns +true+ or +false+ depending on whether the authorization is granted.
    def authorize!
      authorizable? && increment!(:access_counter) ? true : false
    end
    
    private
    
    # Populating the secret automatically and zero'ing the access_counter (otherwise it might turn out to be NULL)
    def set_defaults
      self.secret = SecureRandom.hex(15)
      self.access_counter = 0
    end

    attr_accessible :digital, :line_item, :secret

  end
end

app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do
  
  has_many :digital_links, :dependent => :destroy
  after_save :create_digital_links, :if => :digital?
  
  def digital?
    variant.digital?
  end
  
  private
  
  # Create the download link for this item if it is digital.
  def create_digital_links
    digital_links.delete_all

    variant.digitals.each do |digital|
      self.quantity.times do
        digital_links.create!(:digital => digital)
      end      
    end
  end
  
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  # all products are digital
  def digital?
    line_items.map { |item| return false unless item.digital? }
    true
  end
  
  def some_digital?
    line_items.map { |item| return true if item.digital? }
    false
  end

  # UPGRADE_CHECK
  # TODO this works as of spree 1.1.1; make sure to check the original function on upgrade

  def available_shipping_methods(display_on = nil)
    return [] unless ship_address
    all_methods = Spree::ShippingMethod.all_available(self, display_on)
    puts "ALL METHODS #{all_methods.count} #{display_on}"
    if self.digital?
      all_methods.detect { |m| m.calculator.class == Spree::Calculator::DigitalDelivery }.try { |d| [d] } || all_methods
    else
      all_methods
    end
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :digitals, :through => :variants_including_master
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  
  has_many :digitals, :dependent => :destroy
  after_save :destroy_digital, :if => :deleted?
  
  # Is this variant to be downloaded by the customer?
  def digital?
    digitals.present?
  end
  
  private
  
  # Spree never deleted Digitals, that's why ":dependent => :destroy" won't work on Digital.
  # We need to delete the Digital manually here as soon as the Variant is nullified.
  # Otherwise you'll have orphan Digitals (and their attached files!) associated with unused Variants. 
  def destroy_digital
    digitals.map &:destroy
  end

end

app/controllers/spree/admin/digitals_controller.rb
module Spree
  class Admin::DigitalsController < Spree::Admin::ResourceController
    belongs_to "spree/product", find_by: :permalink
    
    protected
      def location_after_save
        admin_product_digitals_url(@product)
      end
  end
end

app/controllers/spree/digitals_controller.rb
module Spree
  class DigitalsController < Spree::BaseController
    ssl_required :show
  
    def show
      link = DigitalLink.find_by_secret(params[:secret])

      if link.present? and link.digital.attachment.present?
        attachment = link.digital.attachment

        # don't authorize the link unless the file exists
        # the logger error will help track down customer issues easier

        if File.file?(attachment.path)
          if link.authorize!
            send_file attachment.path, :filename => attachment.original_filename, :type => attachment.content_type and return
          end
        else
          Rails.logger.error "Missing Digital Item: #{attachment.path}"
        end
      end
      
      render :unauthorized
    end
    
  end
end

app/views/spree/admin/digitals/_digital.html.erb
<% if digital.attachment_file_name.present? %>
  <%= digital.attachment_file_name %> (<%= number_to_human_size(digital.attachment_file_size) %>)
<% else %>
  <%=t 'broken_file' %>
<% end %>

app/views/spree/admin/digitals/_form.html.erb
<div>
  <div>
    <%= form_for(:digital, :url => admin_product_digitals_path(@product), :method => :create, :multipart => true ) do |f| %>
    <fieldset>
      <legend><%= Spree::Variant.model_name.human %> "<%= variant.options_text %>"</legend>
      
      <%= f.field_container :current_file do %>
      <strong><%=t 'files' %>:</strong>
      <% if variant.digital? %>
      <ul>
        <% variant.digitals.each do |digital| %>
        <li>
         <%= render digital %>&nbsp;&nbsp;
         <%= link_to t("delete_file"), admin_product_digital_url(@product, digital), :confirm => t('delete_file_cofirmation', :filename => digital.attachment_file_name), :method => :delete %>
       </li>
       <% end %>
     </ul>
     <% else %>
     <%=t 'none' %>
     <% end %>
     <% end %>

     <p class="form-buttons">
      <%= f.field_container :file do %>
      <%= f.label :file, t("new_file") %> <span class="required">*</span><br/>
      <%= f.file_field :attachment %>
      <% end %>

      <%= hidden_field_tag 'digital[variant_id]', variant.id %>

      <%= button t('spree_digital.upload') %>
    </p>

  </fieldset>
  <% end %>
</div>

app/views/spree/admin/digitals/index.html.erb
<%= render :partial => 'spree/admin/shared/product_sub_menu' %>
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Digital Versions"} %>

<% if @product.has_variants? %>

  <% for variant in @product.variants do %>
    <%= render 'form', :variant => variant %>
  <% end %>

<% else %>
  This product has no variants.

 <% if @product.master.digital? %>
    A digital version of this product currently exists:
    <%= render @product.master.digitals %>
  <% end %>

  <%= render 'form', :variant => @product.master %>

<% end %>

app/views/spree/digitals/_digital.html.erb
<% if digital.attachment_file_name.present? %>
  <%= digital.attachment_file_name %> (<%= number_to_human_size(digital.attachment_file_size) %>)
<% else %>
  <%=t 'broken_file' %>
<% end %>